#include <iostream>
#include <string>

// Declare the external launcher routing function from EngineLauncher.cpp
void launchSelectedEngine(const std::string& configPath);

// ----------------------------------------------------
#if defined(__ANDROID__) || defined(ANDROID)
// ----------------------------------------------------
// TARGET 1: ANDROID JNI BRIDGE (Called instantly by your Game Turbo Activity)
#include <jni.h>

extern "C" JNIEXPORT void JNICALL
Java_com_game_gameturbo_MainActivity_syncAndLaunchEngine(JNIEnv* env, jobject thiz) {
    std::cout << "[Jay Engine] Android Game Turbo triggered launcher boot pipeline." << std::endl;
    
    // Android reads the dynamic settings cache path generated by your app UI
    // Internal path format: /data/data/com.game.gameturbo/files/turbo_config.json
    std::string androidConfigPath = "/data/data/com.game.gameturbo/files/turbo_config.json";
    
    // Divert execution flow to your separate module router
    launchSelectedEngine(androidConfigPath);
}

// ----------------------------------------------------
#else
// ----------------------------------------------------
// TARGET 2: WINDOWS STANDALONE DESKTOP ENTRY
int main(int argc, char* argv[]) {
    std::cout << "========================================" << std::endl;
    std::cout << "  GLOBAL CODE JAY ENGINE - WINDOWS BOOT " << std::endl;
    std::cout << "========================================" << std::endl;
    
    // Windows desktop reads the local json config folder tree
    std::string windowsConfigPath = "turbo_config.json";
    
    // Divert execution flow to your separate module router
    launchSelectedEngine(windowsConfigPath);
    
    return 0;
}
#endif

